export const EXCLUDE_PATTERNS = [
  /node_modules/,
  /\.git/,
  /System Volume Information/,
  /\$Recycle\.Bin/,
  /Windows\/System32/,
  /Windows\/SysWOW64/,
  /Windows\/WinSxS/,
  /Program Files\/Windows Defender/,
  /Program Files\/Microsoft/,
  /Program Files \(x86\)\/Microsoft/,
  /Program Files\/Common Files\/Microsoft/,
  /Program Files \(x86\)\/Common Files\/Microsoft/,
  /AppData\/Local\/Microsoft\/Windows/,
  /AppData\/Local\/Temp/,
  /ProgramData\/Microsoft\/Windows/,
  /\/Temp\//i,
  /\/Cache\//i,
  /\/temp$/i,
  /\/cache$/i,
  /\.tmp$/,
  /\.temp$/,
  /\.log$/,
  /Chrome.*\/Cache/,
  /Firefox.*\/cache/,
  /Edge.*\/Cache/,
  /Safari.*\/Cache/,
];

export const CONFIG_PATTERNS = [
  { pattern: /\.config$/i, type: 'Application Config' },
  { pattern: /\.ini$/i, type: 'INI File' },
  { pattern: /\.json$/i, type: 'JSON Config' },
  { pattern: /\.xml$/i, type: 'XML Config' },
  { pattern: /\.yaml$/i, type: 'YAML Config' },
  { pattern: /\.yml$/i, type: 'YAML Config' },
  { pattern: /\.toml$/i, type: 'TOML Config' },
  { pattern: /\.properties$/i, type: 'Properties File' },
  { pattern: /\.conf$/i, type: 'Configuration File' },
  { pattern: /\.cfg$/i, type: 'Configuration File' },
  { pattern: /\.settings$/i, type: 'Settings File' },
  { pattern: /\.plist$/i, type: 'Property List' },
  { pattern: /\.reg$/i, type: 'Registry File' },
  { pattern: /\.prefs$/i, type: 'Preferences File' },
  { pattern: /\.profile$/i, type: 'Profile File' },
  { pattern: /\.rc$/i, type: 'RC Configuration' },
  { pattern: /^\..*rc$/i, type: 'RC Configuration' },
  { pattern: /^\.env$/i, type: 'Environment File' },
  { pattern: /^config$/i, type: 'Config Directory' },
  { pattern: /^settings$/i, type: 'Settings Directory' },
]; 